name: seurat
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-alabaster.base
  - bioconductor-annotationdbi
  - bioconductor-biocparallel
  - bioconductor-genomeinfodbdata
  - bioconductor-glmgampoi
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-orthology.eg.db
  - bioconductor-scrnaseq
  - bioconductor-singlecellexperiment
  - bioconductor-singler
  - bioconductor-celldex
  - bioconductor-rhdf5
  - bioconductor-assorthead
  - bioconductor-spatialexperiment
  - bioconductor-scDblFinder
  - bioconductor-ontoProc
  - r-base=4.4.3
  - r-cluster
  - r-cluster=2
  - r-cowplot
  - r-dplyr
  - r-DT
  - r-essentials
  - r-evaluate>=1.0.3
  - r-farver
  - r-flexmix
  - r-forcats
  - r-future.apply
  - r-ggplot2=3
  - r-ggpubr
  - r-gridextra
  - r-harmony>=0.1
  - r-hdf5r
  - r-httr2
  - r-rcppplanc
  - r-liger
  - r-lubridate
  - r-png
  - r-presto
  - r-purrr
  - r-readr
  - r-remotes
  - r-reticulate
  - r-r.utils
  - r-scales
  - r-seurat=5.3
  - r-signac
  - r-stringr
  - r-tibble
  - r-tidyr
  - r-tinytex
  - scvi-tools=1.2
  - zlib
